sonar.organization=thorsten-klein
sonar.projectKey=thorsten-klein_git-nested

sonar.sources=lib
sonar.tests=test
sonar.python.version=3.10,3.14

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=junit.xml
