#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys
import os

# Add the lib directory to the Python path
lib_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, lib_dir)

from git_nested import main

if __name__ == '__main__':
    sys.exit(main())
